### ISSUE TITLE
Torchvision backend not working.

### ISSUE THREAD

**Issue by kiyoon** [facebookresearch/SlowFast#181]
Hi,

I was using the Kinectics dataloader with torchvision backend.
I had a very similar issue as #148, saying that there's no operator called `probe_video_from_memory`.

```
/opt/conda/conda-bld/pytorch_1587428398394/work/torch/csrc/utils/tensor_numpy.cpp:141: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program.
/opt/conda/conda-bld/pytorch_1587428398394/work/torch/csrc/utils/tensor_numpy.cpp:141: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program.
/opt/conda/conda-bld/pytorch_1587428398394/work/torch/csrc/utils/tensor_numpy.cpp:141: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program.
/opt/conda/conda-bld/pytorch_1587428398394/work/torch/csrc/utils/tensor_numpy.cpp:141: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program.
Failed to decode by torchvision with exception: No such operator video_reader::probe_video_from_memory
Failed to decode by torchvision with exception: No such operator video_reader::probe_video_from_memory
Failed to decode by torchvision with exception: No such operator video_reader::probe_video_from_memory
Failed to decode by torchvision with exception: No such operator video_reader::probe_video_from_memory
Failed to decode the video index 0
Failed to decode the video index 4
Choosing random video of index 21667 instead
Choosing random video of index 14461 instead
Failed to decode the video index 12
Failed to decode the video index 8
Choosing random video of index 14195 instead
Choosing random video of index 15546 instead
Failed to decode by torchvision with exception: No such operator video_reader::probe_video_from_memory

...
```

It used to be `read_video_meta_data_from_memory` but apparently this repository is updated.
I tried using PyTorch 1.4.0 / TorchVision 0.5.0 and PyTorch 1.5.0 / TorchVision 0.6.0 but no luck.
It seems like it's looking for the operator on PyTorch side, not TorchVision, which I don't understand why.

Any thoughts on how to debug and what do check?
Thank you for your support.

**Comment by takatosp1** [comment]
Hi,
There is an update on the API from torchvision side. Could you try to pull the latest version of torchvision?

**Comment by kiyoon** [comment]
Hi @takatosp1,
Is there any reason that you're using the master branch of the TorchVision instead of the stable release?
In the `INSTALL.md` it didn't say that TorchVision has to be the master branch.

Also, I had no luck with trying to install TorchVision from source and TorchVision doesn't have a nightly build on conda.

**Comment by banzhuan37** [comment]
I just ran into the same problem with pytorch1.6.0 torchvision 0.7.0, same output "Failed to decode by torchvision with exception: No such operator video_reader::probe_video_from_memory", if I ran slowfast with pyav backends, it totally works. But I ran X3D with torchvision as data decode backends, it reports errors.

**Comment by banzhuan37** [comment]
> Hi @takatosp1,
> Is there any reason that you're using the master branch of the TorchVision instead of the stable release?
> In the `INSTALL.md` it didn't say that TorchVision has to be the master branch.
> 
> Also, I had no luck with trying to install TorchVision from source and TorchVision doesn't have a nightly build on conda.

have you solved this problem already

**Comment by bbrattoli** [comment]
> I just ran into the same problem with pytorch1.6.0 torchvision 0.7.0, same output "Failed to decode by torchvision with exception: No such operator video_reader::probe_video_from_memory", if I ran slowfast with pyav backends, it totally works. But I ran X3D with torchvision as data decode backends, it reports errors.

Same here! When testing X3D, changing DATA.DECODING_BACKEND from torchvision to pyav solves the issue. However, I would like to use the same setup of the author, so it would be good to check this issue. Thanks!

**Comment by thunder95** [comment]
met same problem here. any solution with torchvision?

**Comment by Note-Liu** [comment]
I meet the same error.

**Comment by kiyoon** [comment]
I haven't tried much further, but I think according to the author's answer, you may have to use newer PyTorch version, like 1.8.1

**Comment by Wunaiq** [comment]
pytorch 1.7.1, torchvision 0.8.2，the error still exists.

**Comment by Kewenjing1020** [comment]
I met this error too. I solved this problem by make the following change in configs/xx.yaml:
```
#  DECODING_BACKEND: torchvision  #comment this line
```

**Comment by junting** [comment]
I have tried to build torchvision from source with ffmpeg4.0 (you need to make sure that the torchvision detects the ffmpeg). Then the problem of `read_video_meta_data_from_memory ` can be solved.

**Comment by zhangzilongc** [comment]
In the official torchvision, "Building with FFMPEG is disabled by default in the latest main. If you want to use the ‘video_reader’ backend, please compile torchvision from source"

**Comment by medhini** [comment]
Facing the same error when using Pytorch 1.11.0 and torchvision 0.12.0. The exact error message is:
`RuntimeError: No such operator video_reader::probe_video_from_memory`

**Comment by dfan** [comment]
Took a crack at fixing it. https://github.com/facebookresearch/SlowFast/pull/541

**Comment by alpargun** [comment]
I am using pytorch 1.12.0 and torchvision 0.13.0 and still receiving the error:

```
Failed to decode by torchvision with exception: '_OpNamespace' object has no attribute 'probe_video_from_memory'
[07/08 19:06:20][WARNING] kinetics.py:  372: Failed to decode video idx 217946 from /home/alp/Desktop/kinetics-dataset/k400/train/playing_ice_hockey/thF1B8Nb8Nw_000023_000033.mp4; trial 99
```

When I changed the backend to PyAV, now I receive the error:
```
Failed to decode by pyav with exception: unsupported operand type(s) for -: 'list' and 'int'
[07/08 19:08:14][WARNING] kinetics.py:  372: Failed to decode video idx 175784 from /home/alp/Desktop/kinetics-dataset/k400/train/playing_flute/5ShceiaaL7s_000011_000021.mp4; trial 99

```

Hence, there is still no fix to this issue in the latest versions of PyTorch and torchvision. I will try the changes @dfan suggested in the pyav_decode() function and update if I can make it run:

> Took a crack at fixing it. #541

**Comment by sourabmaity** [comment]
@alpargun How do you solved second problem 
`Failed to decode by pyav with exception: unsupported operand type(s) for -: 'list' and 'int'`
Pls help me...

**Comment by alpargun** [comment]
Please check out this pull request: https://github.com/facebookresearch/SlowFast/pull/541
I copied and pasted @dfan's changes in the file _slowfast/datasets/decoder.py_

**Comment by bd20222** [comment]
Recompiling torchvision from source still fails. Luckily, alpargun's solution works well for me. Thanks so much.

**Comment by bd20222** [comment]
[UPDATE]

After days of exploring, I found some clues why compiling the torchvision from source fails. 

As suggested [here](https://github.com/pytorch/vision/blob/15a9a93b9e0e6173b936691a2cddced0ecfd271f/setup.py#L378), the torchvision doesn't support compiling from source with MacOS or with Python 3.9. So, you should set up another new env.

Alternatively, simply removing the py39 checking also works well in my case (ubuntu + ffmpeg4.3 installed from conda). Hope this helps.

**Comment by khizar-anjum** [comment]
Changed the backend to pyav and copied the changes from #541 as @alpargun suggested.

**Comment by startrekzl** [comment]
> I am using pytorch 1.12.0 and torchvision 0.13.0 and still receiving the error:
> 
> ```
> Failed to decode by torchvision with exception: '_OpNamespace' object has no attribute 'probe_video_from_memory'
> [07/08 19:06:20][WARNING] kinetics.py:  372: Failed to decode video idx 217946 from /home/alp/Desktop/kinetics-dataset/k400/train/playing_ice_hockey/thF1B8Nb8Nw_000023_000033.mp4; trial 99
> ```
> 
> When I changed the backend to PyAV, now I receive the error:
> 
> ```
> Failed to decode by pyav with exception: unsupported operand type(s) for -: 'list' and 'int'
> [07/08 19:08:14][WARNING] kinetics.py:  372: Failed to decode video idx 175784 from /home/alp/Desktop/kinetics-dataset/k400/train/playing_flute/5ShceiaaL7s_000011_000021.mp4; trial 99
> ```
> 
> Hence, there is still no fix to this issue in the latest versions of PyTorch and torchvision. However, the changes @dfan suggested in the pyav_decode() function in [this pull request](https://github.com/facebookresearch/SlowFast/pull/541) work, and now I am able to run the framework with PyAv backend.
> 
> > Took a crack at fixing it. #541

This solution solved my problem,thank you so much!

**Comment by JingwWu** [comment]
> I have tried to build torchvision from source with ffmpeg4.0 (you need to make sure that the torchvision detects the ffmpeg). Then the problem of `read_video_meta_data_from_memory ` can be solved.

It works for me! Thanks!

**Comment by tonysy** [comment]
@haooooooqi Hi, the torchvision backend is still not working.
Would you like to share the detail environment information?
My current env info:
```
sys.platform : linux
Python : 3.8.13 (default, Mar 28 2022, 11:38:47) [GCC 7.5.0]
CUDA available : False
numpy_random_seed : 2147483648
GCC : gcc (GCC) 7.5.0
PyTorch : 1.10.0+cu111
PyTorch compiling details : PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

TorchVision : 0.11.1+cu111
OpenCV : 4.6.0
MMEngine : 0.2.0
MMClassification : 1.0.0rc2+
FFmpeg: 4.2
```

**Comment by alpargun** [comment]
Hi everyone, now I am finally able to work with both torchvision and PyAV video backends. I created my own fork of slowfast with updated and corrected installation steps (INSTALL.md) [here](https://github.com/alpargun/SlowFast).
I hope my documentation for the installation process helps you.

**Comment by chenfanbraveheart** [comment]
@alpargun  your solution work for me, thank you so much!

**Comment by khizar-anjum** [comment]
If people are still having problems with alpargun's solution, please see my detailed comment at https://github.com/facebookresearch/SlowFast/issues/551#issuecomment-1374075371.

**Comment by adildahlan** [comment]
If you had been struggling with this, try installing torchvision and pytorch via the command in https://pytorch.org/get-started/previous-versions/.
Use the latest version and walk backwards until the code compiles. This worked for me: `conda install pytorch==2.0.0 torchvision==0.15.0 torchaudio==2.0.0 pytorch-cuda=11.8 -c pytorch -c nvidia`
I hope this helps!

**Comment by YHJ898** [comment]
Any updates on this? I get the error: `Failed to decode by torchvision with exception: '_OpNamespace' 'video_reader' object has no attribute 'probe_video_from_memory'` when using the torchvision backend and `pyav with exception: unsupported operand type(s) for -: 'list' and 'int'` with PyAv. I've followed the installation instructions and  tried the versions that @adildahlan mentioned. Is there any hints how to overcome this issue?

**Comment by alpargun** [comment]
Have you tried following the installation steps in my fork: https://github.com/alpargun/SlowFast/blob/main/INSTALL.md

**Comment by YHJ898** [comment]
> Have you tried following the installation steps in my fork: https://github.com/alpargun/SlowFast/blob/main/INSTALL.md

Your instructions worked, thanks a lot!

**Comment by farazBhatti** [comment]
@alpargun I ve copy pasted you code in decoder.py but  still getting the same issue.

**Comment by farazBhatti** [comment]
ok , error solved, I was using 'trochvsion' for decoding instead of pyav. change line in config/default.py
`_C.DATA.DECODING_BACKEND = "pyav"#"torchvision"`

**Comment by huwenfeng233** [comment]
> The culprit is due to the changes in commit [99a655bd533d7fddd7f79509e3dfaae811767b5c](https://github.com/facebookresearch/SlowFast/commit/99a655bd533d7fddd7f79509e3dfaae811767b5c) for adding unsupervised training. `num_frames` is now a list, and the torchvision implementation is updated, but not the pyav. See https://github.com/facebookresearch/SlowFast/blob/main/slowfast/datasets/decoder.py#L295-L337 vs. https://github.com/facebookresearch/SlowFast/blob/main/slowfast/datasets/decoder.py#L417-L429.
> 
> `num_frames - 1` doesn't work anymore since num_frames isn't an int anymore. @feichtenhofer could you consider fixing this as it seems the torchvision backend doesn't work without building torchvision from source? A lot of us are still using pyav as the backend.

it workd when i change code in slowfast/datasets/decoder.py ！

**Comment by Hemilibeatriz** [comment]
> > The culprit is due to the changes in commit [99a655bd533d7fddd7f79509e3dfaae811767b5c](https://github.com/facebookresearch/SlowFast/commit/99a655bd533d7fddd7f79509e3dfaae811767b5c) for adding unsupervised training. `num_frames` is now a list, and the torchvision implementation is updated, but not the pyav. See https://github.com/facebookresearch/SlowFast/blob/main/slowfast/datasets/decoder.py#L295-L337 vs. https://github.com/facebookresearch/SlowFast/blob/main/slowfast/datasets/decoder.py#L417-L429.
> > `num_frames - 1` doesn't work anymore since num_frames isn't an int anymore. [@feichtenhofer](https://github.com/feichtenhofer) could you consider fixing this as it seems the torchvision backend doesn't work without building torchvision from source? A lot of us are still using pyav as the backend.
> 
> it workd when i change code in slowfast/datasets/decoder.py ！

did you compile torchvision from source code? which backend did you use? `pyav` or `torchvision`
